# Environment where the service is running
env: local

# Listening port of the serivce
http:
  port: "8081"

# The project artifact and version data 
project:
  artifact: "${project.artifactId}"
  version: "${project.version}"
  
# The RAML API and autodiscovery
api:  
  group: "${restconnector.api.spec.group}"
  artifact: "${restconnector.api.spec.artifact}"
  version: "${restconnector.api.spec.version}"
  spec: "resource::${api.group}:${api.artifact}:${api.version}:raml:zip:api.raml"
  id: "0"

# Service messages
messages:
  record-created-success: "The item was created successfully"
  record-deleted-success: "The item was deleted successfully"
  record-doesnt-exist-relations: "The record does not exist or has relations with other resources"
  record-error: "There was a problem while trying to create the record"

# All the below properties should be added as JVM arguments / Environment Properties.
# Example: -Dsalesforce.user=myuser -Dsalesforce.password=mypassword
# Components to configure: Salesforce connector, OpenTelemtry connector, logzio (logging platform)
