name: Build
 
on:
  push:
    branches: [ "main" ]

jobs:
  Mulesoft:
    uses: jpontdia/common-devops/.github/workflows/mule-build.yml@main
    with:
      keyvault-key: jpworks-keyvault
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}