name: Build and deploy to Anypoint Exchange
 
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  dev-testing:
    name: Development testing
    runs-on: ubuntu-latest
    steps:
      - name: Get the source code
        uses: actions/checkout@v3

      - name: Install API Functional Monitoring
        run: |
          curl -o- 'https://s3.amazonaws.com/bat-wrapper/install.sh' | bash
          echo "bat -version: $(bat -version)"